########################################
######### THAT'S AN EXAMPLE!!! #########
########################################

### Browsers config
browsers:
  - type: chrome
    use: true
    vnc-image:
      enable: true # download VNC version of webdriver
      versions:
        #highest: true # highest (highest browser version); array with browser versions [97.0]
        range:
          min: 90.0
          max: latest
          ignore: [82.0]
    default-version:
      highest: true # highest or custom default browser version (97.0)
    versions: # from min and to max in steps of 1
      range:
        min: 80.0
        max: 99.0
        ignore: [82.0]

  - type: chrome-mobile
    use: true
    default-version:
      highest: true
    versions:
      array: [86.0]

  - type: firefox
    use: true
    vnc-image:
      enable: true
      versions:
        array: [90.0, 91.0, 96.0]
    default-version:
      custom: 92.0 # highest or custom default browser version (96.0)
    versions:
      array: [85.0, 86.0, 87.0, 90.0, 91.0, 92.0, 93.0, 94.0, 95.0, 96.0, latest]

  - type: opera
    use: true
    vnc-image:
      enable: true
      versions:
        highest: true
    default-version:
      highest: true
    versions:
      latest: true


### Aerokube config
aerokube:
  selenoid:
    image-version: latest # not secure, use fix version!
    host-port: 4444

  selenoid-ui: # web user interface
    image-version: latest # not secure, use fix version!
    host-port: 8080

  ggr: # load balancer
    image-version: latest # not secure, use fix version!
    host-port: 4040
    encrypt-connection: false

  ggr-ui: # web user interface
    image-version: latest # not secure, use fix version!
    host-port: 8888


### Hosts config
hosts:
  ggr: # Go Grid Router balancer config
    - ip: 8.8.8.8
    - ip: 127.0.0.1
      domain: localhost
    - domain: ggr-balancer.dev.example.com

  selenoid:
    - region:
        name: us-east
        hosts:
          - ip: 111.111.111.111
            count: 1 # load balancing priority
            cpu-limit: 8 # 1 CPU = 1 browser session
            teams-quota: [ QA_TEAM_1, QA_TEAM_2 ] # quota for ggr config

    - region:
        name: us-west
        hosts:
          - ip: 111.111.111.112
            count: 1 # load balancing priority
            cpu-limit: 8 # 1 CPU = 1 browser session
            teams-quota: [] # quota for ggr config

          - domain: tests-us-west.dev.example.com
            count: 3 # load balancing priority
            cpu-limit: 3 # 1 CPU = 1 browser session
            teams-quota: [] # quota for ggr config
            vnc:
              ip: 111.111.111.113
              port: 6900

    - region:
        name: default
        hosts:
          - ip: 111.111.111.114
            domain: example.com
            cpu-limit: 2
          - ip: 127.0.0.1
            cpu-limit: 6


# Config for teams/users quota
teams-quota:
  - name: QA_TEAM_1
    password: test-selenoid-password

  - name: QA_TEAM_2
    password: test-selenoid-password-2

  - name: DEV_TEAM_1
    password: test-selenoid-password-3